version: "3.4"

services:
  frontend:
    image: materialdashboard2react
    build:
      context: .
      dockerfile: ./Dockerfile
    # environment:
    #   NODE_ENV: production
    ports:
      - 3000:3000
